### ISSUE TITLE
Provide a way to close a client produced by RestClientBuilder#build()

### ISSUE THREAD

**Issue by mkouba** [eclipse/microprofile-rest-client#100]
To close the client instance and all associated resources, e.g. an underlying `javax.ws.rs.client.Client`.

**Comment by kenfinnigan** [comment]
@mkouba, could you propose a PR as to what your ideas for this might be?

I think there's some differences between how RESTEasy and CXF work that could make it tricky

**Comment by mkouba** [comment]
In Thorntail, we've introduced the `org.wildfly.swarm.microprofile.restclient.RestClientProxy` interface implemented by each proxy instance. So you can cast the proxy instance to `RestClientProxy` and close the underlying client. See also http://docs.wildfly-swarm.io/2.0.0.Final/#_restclientproxy and https://github.com/thorntail/thorntail/blob/master/client-apis/microprofile-restclient/src/main/java/org/wildfly/swarm/microprofile/restclient/RestClientProxy.java.

**Comment by kenfinnigan** [comment]
Update code link: https://github.com/smallrye/smallrye-rest-client/blob/master/implementation/src/main/java/io/smallrye/restclient/RestClientProxy.java

**Comment by andymc12** [comment]
Would it work to allow the user to define a `close` method on the client interface?  We would probably need to restrict it so that the actual closing of the method only occurs if there are HTTP method annotations (`@GET`, `@POST`, etc.) on the method - that should ensure backwards compatibility too.

For example:
```
public interface MyClient {

    @GET
    String getSomething();

    void close();
```

Likewise, if the client interface extended `Closeable` or `AutoCloseable`, the inherited `close` method could be used to close the implementation.

**Comment by mkouba** [comment]
Well, this would work but it would also mean "additional" work for users.
