### ISSUE TITLE
Clarify how @Produces and @Consumes should be interpreted

### ISSUE THREAD

**Issue by OndrejM** [eclipse/microprofile-rest-client#109]
I found very little about `@Produces` and `@Consumes` in the spec:
* the Javadoc obviously only specifies the behavior when used in a JAX-RS resource
* the spec PDF only mentions that "a JSON-P MessageBodyReader and MessageBodyWriter will be registered" but does not specify which of them is for which of the annotations
* all the tests that use both the annotations with the same values, so they don't test whether a reader or writer is applied (InterfaceWithProvidersDefined, InterfaceWithoutProvidersDefined)

My issue is for which annotation is a JSON-P MessageBodyReader is applied? For `@Produces` or `@Consumes`? And the same question for a MessageBodyWriter.

I would expect that `@Produces` specifies the MIME-TYPE of the outgoing REST request created when a method is called and that `@Consumes` specifies the value of the `Accept` header to request a specific MIME-TYPE from the server. However, this isn't covered by MP REST client spec at all, not in the PDF text and also in none of the tests. 

For example, Payara does the opposite - `@Produces` is used as a the `Accept` header and `@Consumes` is used as the body MIME-TYPE. This is because Jersey's client proxy interprets them this way: https://github.com/jersey/jersey/blob/master/ext/proxy-client/src/main/java/org/glassfish/jersey/client/proxy/WebResourceFactory.java#L299

**Comment by andymc12** [comment]
> I would expect that @Produces specifies the MIME-TYPE of the outgoing REST request created when a method is called and that @Consumes specifies the value of the Accept header to request a specific MIME-TYPE from the server. However, this isn't covered by MP REST client spec at all, not in the PDF text and also in none of the tests.

@OndrejM I agree. Do you want to open a pull request for this?  I think we would need to put it in the spec document - and maybe add a test or two for it in the TCK.  I don't think we can do anything about the javadoc since `@Consumes` and `@Produces` are JAX-RS annotations.

> For example, Payara does the opposite - @Produces is used as a the Accept header and @Consumes is used as the body MIME-TYPE. This is because Jersey's client proxy interprets them this way

Yes, this seems wrong to me too.  I think Jersey/Payara is still compliant for 1.0 and 1.1 since this has not been defined, but I would expect that this behavior would need to change once the behavior is defined.  I can investigate the CXF behavior, but I think it currently works as expected.

Thanks for bringing this up!

**Comment by kenfinnigan** [comment]
I disagree.

The interface defines what the service is and what it expects. And by using existing JAX-RS annotations we're enforcing the mindset of thinking of the interface as being the service.

One of the goals with this originally was that it was possible for the same interface to be used on the server and by clients, as they had the same concept of the JAX-RS annotation meaning.

If we inverse the meaning, then the re-use across service and client is no longer possible.

Also, I know that RESTEasy proxy generation expects the annotations to be defined as if they were on the service itself

**Comment by andymc12** [comment]
I confirmed today that CXF and OpenLiberty also behave in the same manner as RESTEasy and Jersey - that `@Produces` affects the "Accept" header and `@Consumes` affects the "Content-Type" header.  Given that all three of the major implementations used the same model, and Ken's explanation that we should think of Rest Client interfaces as "server-centric" (i.e. the _service_ produces "application/json", the _service_ consumes "application/xml", etc.), I think that should be the spec-mandated behavior.  I'll plan to create a PR that updates the spec document to clarify the expected behavior of these annotations.

Thanks @OndrejM for raising the issue, and thanks @kenfinnigan for the feedback.
