### ISSUE TITLE
Define how SSE works with the type safe clients

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-rest-client#11]

**Comment by andymc12** [comment]
Unless we decide to put MP Rest Client 1.0 in the MP 2.0 release, I think we should defer this issue.  JAX-RS 2.1 (EE8) has SSE APIs that we should leverage to resolve this issue.

**Comment by johnament** [comment]
@andymc12  we had already decided in an early call to defer this until a release aligned w/ Java EE 8

**Comment by andymc12** [comment]
Something like this would be pretty cool:
https://dzone.com/articles/micronaut-mastery-consuming-server-sent-events-sse

**Comment by andymc12** [comment]
I'd prefer to use the new(-ish) MP Reactive Streams Operators so that SSE events can be "subscribed" to.  Maybe something like this:
```
interface MyClient {

    @GET
    @Path("ssePath")
    @Consumes(MediaType.SERVER_SENT_EVENTS)
    CompletionSubscriber<MyEventType> getEvents();
}
```

Users could then receive events (that the implementation would have already converted to the type they want - without the app code needing to call `inboundSseEvent.readData(MyEventType.class`) via the subscriber.  

We could also make a special case for `CompletionSubscriber<InboundSseEvent>` for cases where the client wants to do the type conversion - the use case for this might be where a service sends events of different types.

**Comment by andymc12** [comment]
I've got a working prototype of this issue going now - including spec text and TCK changes.  One slight change to what I proposed previously - the return type should be `Publisher<?>` instead of `CompletionSubscriber<?>` (or even `Subscriber<?>`).  This is more consistent with the notion that the client interface is a view of the server (which is publishing the SSE events) and allows a client app to subscribe to the publisher in order to consume the events.

The MP Reactive Streams Operators project depends on the org.reactivestreams APIs - and these APIs are basically duplicated/re-pacakaged in Java 9 as the Flow APIs.  So I'm leaning toward making the MP Rest Client 2.0 work with both - since many people will want to run on Java 8 (using org.reactivestreams and the current versions of MP RSO) but other will want to run on Java 9+ and use the Flow API.
