### ISSUE TITLE
checking `response.getLocation()` in `AsyncMethodTest#testAsyncInvocationInterceptorProvider` in 1.1

### ISSUE THREAD

**Issue by michalszynkiewicz** [eclipse/microprofile-rest-client#133]
In MP Rest Client 1.1, the test from the topic has the following assertion:
```java
assertTrue(response.getLocation().getPath().endsWith("/" + threadLocalInt));
```

This check seems to be removed from 1.2 and I failed to find any reason for it in the spec.

Could anyone point me to some docs supporting this check? If it should be removed from 1.1, can we have a maintenance release with such fix (I can create a PR)?

**Comment by andymc12** [comment]
We discussed this in today's meeting, and yes, it is a bug in the 1.1 TCK.  Since Michal's release is imminent, we agreed that this test could be discarded for declaring compatibility with the spec.  But we will need to resolve it - likely by back porting the changes from the 1.2 TCK.  Thanks Michal for catching this.

**Comment by michalszynkiewicz** [comment]
@andymc12 I think this issue is out of date now.
I will close it.
