### ISSUE TITLE
Injection of HttpHeaders in ClientRequestFilter does not work in Jersey

### ISSUE THREAD

**Issue by urbim** [eclipse/microprofile-rest-client#164]
Hi!

[This injection](https://github.com/eclipse/microprofile-rest-client/blob/ffdddfe345fe88f30b4bc58ffcb55896a6edc309/tck/src/main/java/org/eclipse/microprofile/rest/client/tck/providers/ReturnWithAllClientHeadersFilter.java#L34) does not seem to work when using Jersey and consequently the test `ClientHeaderParamTest#testHeaderNotSentWhenExceptionThrownAndRequiredIsFalse` fails. When debugging I can execute `clientRequestContext.getHeaders()` in filter method and get correct headers that the test expects.

I'm not sure if the JAX-RS specification allows this injection, so I'm posting the issue here first. Any help would be greatly appreciated!

**Comment by andymc12** [comment]
Hi @urbim - that is a valid challenge to the TCK.  We do not specify that `@Context` injections should be supported by the providers registered for the rest clients.  You should be able to modify your `tck-suite.xml` file to exclude that test.  

Would you be willing to submit a pull request changing the test filter to obtain the headers from the `ClientRequestContext` that is passed into the `filter` method, rather than using the `@Context` field?

**Comment by urbim** [comment]
Sure! I'll submit a PR as soon as I'm done fixing some other issues, hopefully by the end of the week.

**Comment by jansupol** [comment]
Jersey will allow injection of HttpHeaders in version 2.29 (next release)
