### ISSUE TITLE
Bug with InvokeWithJsonBProviderTest myObject testGet body JSON

### ISSUE THREAD

**Issue by j4fm** [eclipse/microprofile-rest-client#166]
InvokeWithJsonBProviderTest.java@L94-L99

The test myObject JSON in the testGet operation is this effectively this:

{"objectName": "myObject"};"quantity": 17;"date": "2018-12-04";}

Which causes the test to fail with:

Exception with semicolon line 1 position 28

The structure of the test myObject needs to be fixed for the test to pass.

**Comment by j4fm** [comment]
Can be fixed with:
`                .withBody("{" +
                             "\"objectName\": \"myObject\"," +
                             "\"quantity\": \"17\"," +
                             "\"date\": \"2018-12-04\"" +
                          "}")
`

**Comment by pdudits** [comment]
After the JSON is syntactically correct, there are still few issues with mapping definition of `MyJsonBObject`.

1. JSON-B only supports instatiation over public methods and fields. Therefore not having a setter for Name causes the property not being deserialized at all.
2. For same reason, the assertion for `ignoredField` not being changed is trivially satisfied, as conforming implemention cannot set that field without public setter.
3. Deserialization of date into `java.util.Date` is bit controversial, as it is technically a timestamp format. Current version of Yasson will fail complaining that it wouldn't do that by default (See exception below). I will open an issue with them, because I believe this should work. But using `LocalDate` is much safer (and works).
4. The date in assertion does not match its expected format: `new SimpleDateFormat("yyyy.MM.dd").parse("2018-12-04")` 

This is what the exception from point 3:
````
 javax.json.bind.JsonbException: Error parsing class java.util.Date from value: 2018-12-04. 
Check your @JsonbDateFormat has all time units for class java.util.Date type, or consider using org.eclipse.yasson.YassonProperties#ZERO_TIME_PARSE_DEFAULTING.
````

**Comment by Emily-Jiang** [comment]
close as it was fixed
