### ISSUE TITLE
OSGi Import requires CDI API version 1.2, excluding 2.0

### ISSUE THREAD

**Issue by pdudits** [eclipse/microprofile-rest-client#178]
Module depends of `cdi-api` version 1.2, therefore the generated OSGi manifest imports version range `[1.1,2)` for javax.enterprise.inject`.

Since it is part of MicroProfile 2.0, it should import CDI packages also in range `[2.0,3)`, as that is what compliant runtimes would export.

**Comment by andymc12** [comment]
@pdudits Are you referring the the dependency on cdi-api in the pom.xml file?

Technically, I think MP Rest Client can work with older versions of CDI, so I'd be hesitant to limit users to using CDI 2.0+.  

Is it possible to update your tooling so that it generates a wider import range (such as `[1.1,3.0)`)?

**Comment by pdudits** [comment]
I am referring to `Import-Package` directive in OSGi manifest. I believe the import range should be widened in api artifact. Otherwise, when I deploy it into OSGi environment with CDI 2.0 API and runtime, it fails to resolve `javax.enterprise.inject` package `[1.1,2.0)`. I will post a PR for this one.
