### ISSUE TITLE
MP Rest Client overlooks Collection handling in params

### ISSUE THREAD

**Issue by derekm** [eclipse/microprofile-rest-client#217]
Given `@QueryParam("foo") Set<String> foo`, MP Rest Client produces `foo=[foo1, foo2]` instead of `foo=foo1&foo=foo2`.

Jersey WebResourceFactory handles this correctly:
https://github.com/eclipse-ee4j/jersey/blob/master/ext/proxy-client/src/main/java/org/glassfish/jersey/client/proxy/WebResourceFactory.java#L211

**Comment by andymc12** [comment]
As discussed in gitter, this seems like a behavior specific to Jersey.  The behavior in Liberty/CXF is as expected (produces a query string like `foo=foo1&foo=foo2`), which is consistent with the JAX-RS client.

I think the issue is still valid in MP Rest Client, as we should document the behavior and test for it in the TCK if possible.  Additionally, it might be nice to require that implementations support both style of multi-params, and that users could toggle between styles using a MP Config setting.

**Comment by derekm** [comment]
MP Rest Client may wish to specify how various backends expect to receive multi-valued params.

For example, CXF can support `foo=foo1,foo2`:

https://issues.apache.org/jira/browse/CXF-8089

and PHP supports `foo[]=foo1&foo[]=foo2`.

If MP Rest Client is for targeting any web platform, then optionally handling several styles of posting multiple values would be very beneficial.
