### ISSUE TITLE
Define a new name for RegisterProviders

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-rest-client#23]
We're introducing an annotation to use when registering providers.  It was decided that the name `@RegisterProviders` wasn't great, but didn't have a better name.  So for now we're introducing it with this name, however we want to reevaluate before end of release.

So this ticket serves as a placeholder for that change, and will be closed within 1.0 regardless of results.

**Comment by johnament** [comment]
As a part of #25 adding a new `RegisterProvider` annotation.

**Comment by OndrejM** [comment]
@johnament @andymc12 
Do you remember why RegisterProviders wasn't a good name? Is it because it should match what `RestClientBuilder.register` does via builder pattern and that works for more things than just providers? In that case, what about renaming to `@RegisterRestComponent` because the argument to `RestClientBuilder.register` (`Configuration.register`) is named `componentClass`?

**Comment by OndrejM** [comment]
`@WithRestComponent` looks even better than "Register...":

```
@GET
@WthRestComponent(JsonbProvider.class)
@WithRestComponent(MyFeature.class)
@Produces(MediaType.APPLICATION_JSON)
public MyResource getResource() {
...
}
```

**Comment by andymc12** [comment]
I don't think were any strong objects to `@RegisterProvider`, but on one of the earlier calls, some of us just didn't quite like the sound of it, but didn't have any better ideas either.

For my two cents, `@RegisterProvider` has grown on me, but `@WithRestComponent` sounds good too - no strong feelings either way.

**Comment by johnament** [comment]
Agreed on the call, we're ok with the names `@RegisterProvider` and `@RegisterProviders`.  End users should only need to use the repeatable `@RegisterProvider`
