### ISSUE TITLE
Update to Jakarta EE8 APIs for MP 3.3 in Feb 2020

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile-rest-client#231]

**Comment by andymc12** [comment]
@kenfinnigan do you think this will require a new release (i.e. MP Rest Client 1.4)? Or can we update this in a micro release (i.e. 1.3.5)?

As I understand it, the Jakarta EE8 APIs are binary compatible with the Java EE8 APIs, so other than the change to the Maven coordinates, I don't think anything else needs to change, right?

Thanks!

**Comment by kenfinnigan** [comment]
technically it can be micro, but I think to be included in the umbrella they only want major/minor

So it would need to be 1.4 I believe

**Comment by kenfinnigan** [comment]
Does this need to be re-opened @andymc12?

Or MP REST Client isn't doing a 1.x for MP 3.3 now?

**Comment by andymc12** [comment]
@kenfinnigan I'd prefer to wait and do a 2.0 release for the June MP umbrella release.  Other than the Jakarta dependencies (2.0) the only things we have done so far in master are:
* Add `@Target` to `@RestClient` - Issue #232 
* Change in how SPI class is loaded - Issue #248
* Support injection works in `ClientHeadersFactory` - Issue #234 (PR #243 still pending)

I know you had users interested in `@Target` - would you prefer to get that released in February?  Otherwise, I don't think there is really enough content in there to justify a new release yet.  Wdyt?

**Comment by kenfinnigan** [comment]
Ah, yeah I know there are some Quarkus/Kotlin users wanting the `@Target` fix.

If we can do a small minor for MP 3.3 that would be great

**Comment by andymc12** [comment]
This is a breaking-change due to the change in scope for the APIs.  Previously, the APIs included Java EE 7, and used the default Maven ("compile") scope which would package the dependencies with the user-created WAR files.  After this change, the scope is now "provided" which means that the dependencies should be provided by the implementation container.
