### ISSUE TITLE
Registration of JAX-RS Features

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-rest-client#24]
Clarify in the spec that providers and features should both be registered in a client, both via builder and via annotation.

**Comment by OndrejM** [comment]
As I commented in https://github.com/eclipse/microprofile-rest-client/issues/23#issuecomment-349487668, I suggest renaming the `RegisterProvider(s)` annotations because they are also used to register other JAX-RS components like features. My suggestions is to rename to `@RegisterRestComponent` or `@WithRestComponent`

**Comment by johnament** [comment]
What about just `@RegisterComponent`?  However, now that we're mentioning it, one of the things currently missed is custom properties.
