### ISSUE TITLE
How to handle files via MP RestClient?

### ISSUE THREAD

**Issue by RuiBaiXYZ** [eclipse/microprofile-rest-client#261]
How to handle file upload/download via Eclipse Microprofile Rest Client?
Or can give some suggestions?

**Comment by andymc12** [comment]
This is not well defined in the MP Rest Client spec.  Right now it should be possible using implementation-specific (non-portable) options - like https://quarkus.io/guides/rest-client-multipart.

We have had requests to specify how to handle file uploads (multipart attachments) in issue #212. Part of the holdup on this feature is that we'd like to see how the Jakarta JAX-RS community defines it (scheduled for the release after next) so that we can follow suit.

**Comment by DeMol-EE** [comment]
Hello, with the release of Jakarta EE 10 and thereby Jakarta RESTful web services 3.1, I was wondering if there are plans to integrate with the new EntityPart type (or other ways, now supported by the specification)?

**Comment by Emily-Jiang** [comment]
@jamezp @jim-krueger will take a look at this.
