### ISSUE TITLE
Does RestClientBuilder require CDI?

### ISSUE THREAD

**Issue by knutwannheden** [eclipse/microprofile-rest-client#278]
From the specification it isn't quite clear to me whether the `RestClientBuilder` API is expected to work in a standalone environment (i.e. no CDI initialized) or not. Specifically also, can a `RestClientListener` implementation expect to be able to access CDI beans using `CDI.current().select()`?

**Comment by andymc12** [comment]
Hi @knutwannheden - it does not require CDI.  The intent is for all of the "bells and whistles" to be applicable whether the client is running in a CDI-aware environment or a standalone (Java SE) environment - of course in a standalone environment, you would lose the CDI-provided bells and whistles like injection, lifecycle-management, etc.

The `RestClientBuilder ` can be used in either environment, but is primarily targeted for the standalone environment (since it is possible to inject instances of the rest client using CDI).  The `RestClientListener` is intended for either environment, so implementations should only depend on CDI if they are running in a CDI-enabled environment.

We are about to release the MP Rest Client 2.0 - if you can think of a way to make this more clear in the spec or API docs, please let me know - or open a pull request with suggested changes.

Thanks for the question!  Andy

**Comment by knutwannheden** [comment]
Thank you very much for your feedback. Possibly I missed the corresponding section in the specification, but your comment makes it perfectly clear to me.

I was looking at SmallRye's `SmallRyeRestClientListener` which calls `CDI.current().select()` (see https://github.com/smallrye/smallrye-opentracing/blob/662328c061fa41f34ec39a1cfcde358ada496ec0/implementation/src/main/java/io/smallrye/opentracing/SmallRyeRestClientListener.java#L24) and I was unsure whether that is actually "legal" or not.

**Comment by juanmbellini** [comment]
I'm having trouble with `SmallRyeRestClientListener`  also.
I'm trying quarkus, and I'm performing some unit tests over my quarkus poc project. I prefer to create tests woth little dependencies on testing extensions. That's why I'm not using any CDI, but rather instantiate the clients using `RestClientBuilder`.

But, as I have in my classpath `io.quarkus:quarkus-smallrye-opentracing` which adds `SmallRyeRestClientListener`, the `RestClientBuilder#build`  method detects it and tries to register the listener.

However, I think that it is an smallrye's issue. In fact, it is opened here: https://github.com/smallrye/smallrye-opentracing/issues/134

**Comment by jclingan** [comment]
Solved above. Please re-open if still an issue.
