### ISSUE TITLE
Introduce support for HTTP proxies

### ISSUE THREAD

**Issue by gastaldi** [eclipse/microprofile-rest-client#279]
Some environments require HTTP calls to go through an HTTP/S proxy. Right now the 	only way to accomplish this is by using some implementation specific properties while building the RestClient. Here is an example using JBoss RESTEasy Client: 

```java
import static org.jboss.resteasy.client.jaxrs.ResteasyClientBuilder.*;

MyRestClient build = RestClientBuilder.newBuilder()
        .baseUri(UriBuilder.fromUri(baseUri).build())
        .property(PROPERTY_PROXY_HOST, proxyHost)
        .property(PROPERTY_PROXY_PORT, proxyPort)
        .property(PROPERTY_PROXY_SCHEME, proxyScheme)
        .build(MyRestClient.class);
```

It would be nice if the spec could define some standard properties for the proxy parameters (or API changes), so the declarative mode (`@Inject @RestClient`) can also be used.

**Comment by andymc12** [comment]
Hi @gastaldi - this may be a duplicate of issue #55 which will be a part of MP Rest Client 2.0 (you can see the API changes in PR #275).  

This enables the proxy host and port to be specified using the `RestClientBuilder` or using MP Config properties (when injecting using `@RestClient`).  

The 2.0 release is delayed due to the overall MicroProfile Working Group process, but you can experiment with the [latest release candidate](https://github.com/eclipse/microprofile-rest-client/releases/tag/2.0-RC2) to see if this will meet your needs.  The only implementation that I am aware of that implements this is Apache CXF 3.4.0 which is not yet released - you'd either need to build it yourself locally or download the latest snapshot build from here:
https://repository.apache.org/content/groups/snapshots/org/apache/cxf/cxf-rt-rs-mp-client/3.4.0-SNAPSHOT/

If there is something missing in the API or implementation, please let me know.  Thanks!

**Comment by gastaldi** [comment]
@andymc12 thanks for the pointer. Apparently I haven't searched the issues enough before opening this one. It seems to be exactly what I am looking for, so I'll close this one for now and subscribe to the other issue and PR. 

Thank you!
