### ISSUE TITLE
Parameters defined via `@ClientHeaderParam` don't get applied to outbound request

### ISSUE THREAD

**Issue by schoeffm** [eclipse/microprofile-rest-client#288]
Hi everybody,

when using `@RegisterClientHeaders` along with `DefaultClientHeadersFactoryImpl` I expected the factory to behave like it's described in the specification under [Specifying Additional Client Headers](https://download.eclipse.org/microprofile/microprofile-rest-client-2.0-RC2/microprofile-rest-client-2.0-RC2.html#_specifying_additional_client_headers)
> This interface has a single method and takes two read-only MultivaluedMap parameters ... The method should return a MultivaluedMap that contains the headers to merge with this second map for the "final" map of headers to be sent to the outbound processing flow.

Now, when I check the respective [code](https://github.com/eclipse/microprofile-rest-client/blob/master/api/src/main/java/org/eclipse/microprofile/rest/client/ext/DefaultClientHeadersFactoryImpl.java) the second parameter `clientOutgoingHeaders` is actually not used (except for logging) and thus not merged to the output `MultivaluedMap`:
```java
    @Override
    public MultivaluedMap<String, String> update(MultivaluedMap<String, String> incomingHeaders,
                                                 MultivaluedMap<String, String> clientOutgoingHeaders) {

        if (LOG.isLoggable(Level.FINER)) {
            LOG.entering(CLASS_NAME, "update", new Object[]{incomingHeaders, clientOutgoingHeaders});
        }
        MultivaluedMap<String, String> propagatedHeaders = new MultivaluedHashMap<>();
        Optional<String> propagateHeaderString = getHeadersProperty();
        if (propagateHeaderString.isPresent()) {
            Arrays.stream(propagateHeaderString.get().split(","))
                  .forEach( header -> {
                      if (incomingHeaders.containsKey(header)) {
                          propagatedHeaders.put(header, incomingHeaders.get(header));
                      }
                  });
        }
        if (LOG.isLoggable(Level.FINER)) {
            LOG.exiting(CLASS_NAME, "update", propagatedHeaders);
        }
        return propagatedHeaders;
    }
```
Thus, none of the header-values configured i.e. via `@ClientHeaderParam` get merged to the outbound request.

Is this behavior of `DefaultClientHeadersFactoryImpl` intended (since one can register its own Factory it's actually easy work around ... but still is surprising)?

 Regards

**Comment by kenfinnigan** [comment]
I actually just hit this myself and was going to raise an issue.

@andymc12 do you agree that nothing in the spec says it should behave this way?

Will look to provide a fix in the morning, as this should be done for 2.0 in MP 4.0

**Comment by andymc12** [comment]
Hi @kenfinnigan, @schoeffm, this is actually working as designed.  The intent for the "update" method was never to do the merge itself (otherwise, we would've named the method "merge") - the MP Rest Client implementation is required to do the merge. The returned map is only supposed to present the new headers to be sent.

One of the reasons for passing in the non-propagated headers map is to allow custom implementations to make decisions based on those headers.  The default implementation does not make such decisions - it only propagates headers as specified by MP Config.

Open Liberty's implementation (based on Apache CXF) performs this merge.  If we require that implementations of ClientHeadersFactory must perform the merge instead, that will be a breaking change for implementers and for users (I know of a few users who have already written custom ClientHeadersFactory implementations that would now need to perform the merge themselves) - and if we decide to do that, we should change the method name from "update" to "merge" to accurately reflect the intent of the method. Personally, I would lean towards leaving this as it is - or perhaps clarifying it better in the spec and/or javadoc that the MP Rest Client implementation (not this method) is intended to merge the headers.

**Comment by kenfinnigan** [comment]
Interesting, is that explicitly stated in the spec anywhere as I didn't see anything when I looked last night.

If we're completely gutting the headers to be passed, maybe `replace` as a method name makes more sense?

I don't mind what approach is taken, I just think right now it's not clear that `@RegisterClientHeaders` will blat out any headers from `@ClientHeaderParam` that were set. Particularly as the custom header factory in the TCK explicitly retains those values.

**Comment by andymc12** [comment]
The ClientHeadersFactory isn't removing/gutting headers from a request - only adding/updating them. The spec says:
> The second map represents the headers to be sent, and it contains headers that have been specified via @ClientHeaderParam, @HeaderParam, @BeanParam, etc. The method should return a MultivaluedMap that contains the headers to merge with this second map for the "final" map of headers to be sent to the outbound processing flow. Providers such as filters, interceptors, message body writers, etc. could still modify the final map of headers prior to sending the HTTP request.

When I wrote "The method should return a MultivaluedMap that contains the headers to merge with this second map for the "final" map of headers to be sent to the outbound processing flow", I was trying to state that the implementation of this interface would return the new/updated headers and that the MP Rest Client implementation would perform the merge. 

I still think "update" makes the most sense since we are updating the headers to be sent.  "Replace" sounds more like "merge" to me - where the method will see the headers from JAX-RS and the headers already specified by the user (via `@HeaderParam` or `@ClientHeaderParam`) and will decide which ones to keep and which ones to toss.  

What if I clarified the spec to say "The method should return a MultivaluedMap that contains the new or updated headers that the MP Rest Client implementation must merge with this second map for the "final" map of headers to be sent to the outbound processing flow"?

**Comment by kenfinnigan** [comment]
Maybe we need to come at this from another angle, and not provide the default factory that ignores the current set of "outgoing" headers?

Then it forces implementations to do what is needed instead of relying on the default?

**Comment by kenfinnigan** [comment]
Do you have any recollection on this @michalszynkiewicz?

**Comment by michalszynkiewicz** [comment]
Sadly I don't remember much about it but can take a look at the code and spec if needed.

**Comment by kenfinnigan** [comment]
@andymc12 do you have a link to what OpenLiberty/CXF does?

In terms of spec wording, I think "The method should return a `MultivaluedMap` that contains the headers to merge with this second map for the "final" map of headers to be sent to the outbound processing flow." needs to change to "The method should return a `MultiValuedMap containing the "final" map of headers to be sent to the outbound processing flow", or something like that.

In addition, the following paragraph that talks about the `DefaultClientHeadersFactoryImpl` should explicitly state that the default implementation ignores any headers from `@ClientHeaderParam`, etc, and only propagates the headers defined in the configuration property.

In addition, the javadoc on `ClientHeadersFactory` should be aligned with the new spec text and `DefaultClientHeadersFactoryImpl` updated to explicitly state it ignores any headers present on the outgoing map parameter.

If that sounds reasonable, I can adjust the PR accordingly.

**Comment by andymc12** [comment]
@kenfinnigan 
It was initially put into CXF during the MP Rest Client 1.2 release back in December 2018:
https://github.com/andymc12/cxf/blob/f29e60b167440662b1406693cda4c44c06df78e7/rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/proxy/MicroProfileClientProxyImpl.java#L400

It has since been refactored and is now in:
https://github.com/andymc12/cxf/blob/ad7816167c17178de1e1d0eea4f60c1001921ef3/rt/rs/microprofile-client/src/main/java/org/apache/cxf/microprofile/client/proxy/MicroProfileClientProxyImpl.java#L458

CXF 3.4.0 implements MP Rest Client 2.0-RC2 (which was approved for GA pending the working group).  I'd rather not make a breaking change at this stage that will require CXF users to change.  I'm ok with clarifying the current expected behavior in the spec for the 2.0 release, but if we are going to change the behavior of this method, we need to do it in a 3.0 release.

**Comment by andymc12** [comment]
Ah, thanks for updating the pull request.  I see what you mean now.  I'll approve the PR.

As for future direction, it might be good to get all MP Rest Client implementations on the same page.  Currently CXF merges the headers returned from the `update` method with the headers specified by "normal" means (`@HeaderParam`, `@ClientHeaderParam`, etc.) while it looks like RESTEasy and Jersey do not - they expect the `ClientHeadersFactory` implementation code to do the merging.  

Thinking more about this... what if we added default method to the `ClientHeadersFactory` interface that does the merge - ex:
```
default MultivaluedMap<String, String> merge (MultivaluedMap<String, String> jaxrsHeaders, MultivaluedMap<String, String> clientOutgoingHeaders) {
    MultivaluedMap<String, String> allHeaders = update(jaxrsHeaders, clientOutgoingHeaders);
    return allHeaders.putAll(clientOutgoingHeaders);
}
```

This would allow CXF to keep it's existing behavior, and allow Jersey and RESTEasy to invoke the `merge` method and then the behavior is consistent across all implementations without breaking any users or implementations.  Wdyt?

**Comment by kenfinnigan** [comment]
I've actually just submitted a PR to RESTEasy to perform the merge if the `DefaultClientHeadersFactoryImpl` is used.

It's definitely something we can look into post 2.0, we'd need to decide whether it makes sense to favor `clientOutgoingHeaders` or output of `update()`.
