### ISSUE TITLE
Add support for proxy and non proxy hosts

### ISSUE THREAD

**Issue by Ravisankar-Challa** [eclipse/microprofile-rest-client#55]

**Comment by johnament** [comment]
@Ravisankar-Challa could you provide some more information here?

**Comment by andymc12** [comment]
I think for MP Rest Client 1.0, we'll implement this item similarly to issue #53 - where proxy configuration of proxy host/port/etc is done via vendor-specific properties.  For many implementations, the proxyHost/proxyPort system properties will work (assuming that the underlying client implementation uses HttpUrlConnection).  Otherwise clients could use vendor-specific properties via the `RestClientBuilder.property(String, Object)` API.

For future versions of the MP Rest Client, we should consider making this more standard - maybe a new method(s) on `RestClientBuilder` for proxy config.

**Comment by Ravisankar-Challa** [comment]
@johnament 
Thanks for clarifying that future versions provide a standard (vendor neutral) way of specifying proxy and non proxy hosts.

**Comment by rcgitaccounnt** [comment]
Dears 
Kindly let me know how is this issue resloved  , what is the method  RestClientbuilder to set in the proxy host and the port  . I still have the issue  .

**Comment by andymc12** [comment]
@rcgitaccounnt Thanks for the post.  I'll try to get something written up for this for the 2.0 release.

In short, I think we will need new `proxyHost(...)` and `proxyPort(...)` methods on the `RestClientBuilder` and the similar MP Config properties.

The deadline for 2.0 is coming quickly though, so I cannot make any promises.  The changes to the spec document and API are fairly simple, but testing an implementation with the TCK may be somewhat complex.

**Comment by rcgitaccounnt** [comment]
@andymc12   Thanks for your reply  . hopefully awaiting in the release 2.0

**Comment by andymc12** [comment]
After some more thought, I will plan to use a single `proxyServer(String host, int port)` method.  This makes it one less line of code for most users, and avoids scenarios where the port is specified but the hostname isn't, etc.

**Comment by rcgitaccounnt** [comment]
@andymc12  Thanks for your support

**Comment by ambition-consulting** [comment]
Was proxy authentication forgotten or isn't it a feature obviously required in companies that use proxies?
