### ISSUE TITLE
Filter support

### ISSUE THREAD

**Issue by johnament** [eclipse/microprofile-rest-client#6]
Explain how JAX-RS client request filters, client response filters are applied.
Determine if another filter type is required.

**Comment by johnament** [comment]
Possible solutions:
- Add as annotations on the interface, so that the configuration is consistent, avoiding the client builder pattern.

Stretch for 1.0

**Comment by johnament** [comment]
This was done as a part of #7

**Comment by mohhef** [comment]
Hello,

I have a microprofile rest client that gets called from a rest endpoint, the microprofile looks like:

@ApplicationScoped
@RegisterRestClient(configKey = "hello.webtext")
public interface helloClient {
  @POST
  @Path("/hello.html")
  @Consumes({MediaType.APPLICATION_FORM_URLENCODED})
  @Produces({MediaType.TEXT_HTML})
  Response sendText(@FormParam("a") String a);
}

How can i make my ContainerRequestFilter detect this request?

**Comment by andymc12** [comment]
Hi @mohhef - I'd like to clarify your question.  Are you wanting a ClientRequestFilter to execute when invoking the `sendText(...)` method, or a ContainerRequestFilter that is invoked before the JAX-RS resource method is invoked?

If the former, the easiest way is to use the `@RegisterProviders(MyClientRequestFilter.class)` annotation on the client interface.  This will only work if you are using CDI to inject the client.  If you are using `RestClientBuilder` to build the client instance, then you will need to use the `register` method to register the filter like this:
```
helloClient myClient = RestClientBuilder.newBuilder()
                                        .baseUri(someUri)
                                        .register(MyClientRequestFilter.class)
                                        .build(helloClient.class);
```

If the latter, that's more of a JAX-RS question, but you would need to register either by using JAX-RS's auto-discovery mechanism (just put `@Provider` on the ContainerRequestFilter impl class) or you would need to return it from the `getClasses` or `getSingletons` method from the `Application` subclass.  

Hope this helps!

**Comment by mohhef** [comment]
Thank you for your reply that helps. I have used the @registerProvider for it to work.
I currently have this:

```
@Provider
@Slf4j
public class WebTextClientFilter implements ClientRequestFilter, ClientResponseFilter {

    @Context
    private ResourceInfo resourceInfo;

    @Override
    public void filter(ClientRequestContext clientRequestContext) throws IOException {

    }

```

What i am trying to do is I want to log the input parameters, I can clearly see all the @formParam being captured  here:
![image](https://user-images.githubusercontent.com/41707836/98777783-58c58f00-23bf-11eb-8225-2a522e619684.png)
However I have no idea how can i access them.


I am also trying to log the response after the response, however I was not able to find a proper way to do that. I have tried using this:

 ```
   public InterceptingInputStream(final InputStream source) throws IOException {
        this.source = new BufferedInputStream(source); // to ensure mark() is supported
        this.source.mark(MAX_ENTITY_SIZE + 1);
        final byte[] entity = new byte[MAX_ENTITY_SIZE + 1];
        final int entitySize = this.source.read(entity);
        final StringBuilder s = new StringBuilder(MAX_ENTITY_SIZE);
        s.append(new String(entity, 0, Math.min(entitySize, MAX_ENTITY_SIZE), Charset.defaultCharset()));
        if (entitySize > MAX_ENTITY_SIZE) {
            s.append("...more...");
        }
        this.intercepted = s.toString();
        this.source.reset();
    }
```

which is supposed to take the input stream and build a string from it, however i keep getting the response string as "000/n" although it is otherwise.

Please guide me on what should i do if i want to get the request parameters and response body.

**Comment by andymc12** [comment]
Since you are using CDI, the easiest thing to do is probably use a CDI interceptor.  The reason I suggest that approach is that it will allow you access to the Java method parameters and return objects directly - client request filters give you access to the same data, but it is in the context of an HTTP request (or response) rather than Java objects.  That means that you would need to use different APIs to access form parameters (like your example) vs HTTP header parameters vs path parameters, etc.  

The interceptor is also invoked in a different order than client request filters.  CDI interceptors would be invoked around the invocation of the rest client method.  Client request filters are invoked after invoking the rest client method.  One is not any better than the other, but just different - client request filters would allow you to manipulate the request prior to sending, and manipulate the response prior to the rest client method returning.
